language: node_js
node_js:
  - 'lts/*'

install:
  - npm install

services:
  - mongodb

scripts: 
  - npm run test

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  
after_success:
  - coveralls < coverage/lcov.info
